### ISSUE TITLE
Running a single test leads to error in Eclipse

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/reddeer#1856] opened 2017-11-10 08:50 UTC
While it's possible to run a test class from Eclipse if you try to select a single method this will lead to an error.
The error is:
`java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=testEditCPURequestViaContextMenuOfService default], {ExactMatcher:fDisplayName=testEditCPURequestViaContextMenuOfService default(org.jboss.tools.openshift.ui.bot.test.application.v3.advanced.EditResourceLimitsTest)]] from org.junit.internal.requests.ClassRequest@556ae52d
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:80)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:71)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:523)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by rawagner** [comment] 2017-11-10 08:59
Dupe of https://github.com/eclipse/reddeer/pull/1832

**Comment by odockal** [comment] 2017-11-16 09:24
#1832 was resolved. Closing this one as well.

**Closed by odockal** 2017-11-16 09:24 UTC
